config/routes.rb
Rails.application.routes.draw do




  get 'our_partners/index'

  get 'confirmation/index'

  get 'send/index'

  resources :sales
  resources :banks
  devise_for :users , controllers: {
      registrations: 'users/registrations'
  }


  root 'welcome#welcome'
  get 'welcome/welcome'
  resources :products
  resources :users
  resources :sale_products

  get '/users/reset_password/:id' , to: 'users#reset_password'
  get '/users/active/:id' , to: 'users#active'
  get '/users/superactive/:id' , to: 'users#superactive'
  get '/send/index' , to: 'send#index'
  get 'clean' => "products#clean"
  get '/sales/12565/index2' , to: 'sales#index2'

  get '/send/:id/sell' , to: 'send#sell'

  get '/sales/:id/read' , to: 'sales#read'


  get '/users/:id' , to: 'users#show'
  get '/tree/:id' , to: 'tree#index'
  get '/welcome/:id' , to: 'welcome#index'
  post  'saleproducts/create', to: 'saleproducts#create'
  get   'sale_products/:id/destroy/:product_id' , to: 'sale_products#destroy'
  get   'sale_products/:id/decrement/:product_id' , to: 'sale_products#decrement'
  get   'sale_products/:id/increment/:product_id' , to: 'sale_products#increment'

  get '/fetch_products' => 'products#from_category', as: 'fetch_products'
    get "/index.html" => "static#index"
    get "/index2.html" => "static#index2"
    get "/index3.html" => "static#index3"
    get "/form.html" => "static#form"
    get "/form_advanced.html" => "static#form_advanced"
    get "/tables.html" => "static#tables"
    get "/tables_dynamic.html" => "static#tables_dynamic"
    get "/general_elements.html" => "static#general_elements"
    get "/media_gallery.html" => "static#media_gallery"
    get "/typography.html" => "static#typography"
    get "/icons.html" => "static#icons"
    get "/glyphicons.html" => "static#glyphicons"
    get "/widgets.html" => "static#widgets"
    get "/invoice.html" => "static#invoice"
    get "/inbox.html" => "static#inbox"
    get "/calendar.html" => "static#calendar"
    get "/chartjs.html" => "static#chartjs"
    get "/chartjs2.html" => "static#chartjs2"
    get "/morisjs.html" => "static#morisjs"
    get "/echarts.html" => "static#echarts"
    get "/other_charts.html" => "static#other_charts"
    get "/fixed_sidebar.html" => "static#fixed_sidebar"
    get "/fixed_footer.html" => "static#fixed_footer"
    get "/kitchen_sink" => "static#kitchen_sink"
    get "/kitchen8_sink" => "static#kitchen8_sink"
    get   '/',                                    to: "static#index"
    get "/firms/mother_firms",                        to:'firms#mother_firms'
    get "/firms/_categories",                        to:'firms#_categories'
    get "/banks/25/send_activation",              to:'banks#send_activation' , as: "send_activation"
    post  'banks/activations', to: 'banks#activations'
    post  'users/activations' , to: 'users#activations'
    post  'confirmation/ID' , to: 'confirmation#ID'


end

app/views/layouts/shared/_footer.html.erb
<div class="pull-right">
  LITGHTHOUSE - Multi level marketing site by NSTECHNOLOGY
</div>
<div class="clearfix"></div>

app/views/layouts/shared/_leftnav.html.erb
<div class="navbar nav_title" style="border: 0;">
  <a href="<%=root_url%>" class="site_title"><img src="<%= asset_path ('LightHouse_logo.png') %>" style="height: 30px; width: 30px; margin-left: 10px;"> <span>LightHouse</span></a>
</div>

<div class="clearfix"></div>

<!-- menu profile quick info -->
<div class="profile clearfix">
  <div class="profile_pic">
    <img src="<%= current_user.image.url %>" alt="..." class="img-circle profile_img">
  </div>
  <div class="profile_info">
    <span>Bienvenue,</span>

    <h2><%= current_user.first_name %> <%= current_user.last_name %></h2>
  </div>
</div>
<!-- /menu profile quick info -->

<br />

<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <ul class="nav side-menu">
      <%if current_user.activate%>
      <li><a><i class="fa fa-home"></i> Organisation <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><%= link_to 'Dashboard', "/welcome/#{current_user.id}" %></a></li>
          <%if current_user.role == "admin"%>
            <li><%= link_to 'Liste des utilisateurs', users_path%></a></li>
            <%else%>
            <li><%= link_to 'Mon equipe', users_path%></a></li>
            <%end%>
          <%if current_user.treeactivation %>
          <li><%= link_to 'Mon arbre', "/tree/#{current_user.id}" %></a></li>
          <%end%>
        </ul>
      </li>
        <%else%>
      <li><a><i class="fa fa-bar-chart-o"></i> Organisation <span class="label label-danger ">Non Activé</span></a>

      </li>
        <%end%>

      <%if current_user.activate%>
      <li><a><i class="fa fa-desktop"></i> Store <span class="fa fa-chevron-down"></span></a>
       <ul class="nav child_menu">
          <li><%= link_to 'Produits et Services', products_path%></a></li>
         <li><%= link_to 'Mon pannier', sales_path%></a></li>
         <li><%= link_to 'Mes ventes', "/send/index"%></a></li>

        </ul>
      </li>

      <% else %>
        <li><a><i class="fa fa-desktop"></i> Store <span class="label label-danger ">Non Activé</span></a>

        </li>
      <% end %>

      <%if current_user.activate%>
      <li><a href="<%= banks_path %>"><i class="fa fa-bank" ></i> Bank </a>
      <% else %>
        <li><a><i class="fa fa-bank" ></i> Store <span class="label label-danger ">Non Activé</span></a>

        </li>
      <% end %>
      </li>
      <li>
        <a href="<%= our_partners_index_path %>"><i class="fa fa-group"></i> Nos partenaires </a>

      </li>
      <li><a><i class="fa fa-gift"></i> Outils Promotionnel <span class="label label-info pull-right ">Bientôt</span></a>

      </li>

      <li><a><i class="fa fa-envelope"></i> E-mailing <span class="label label-info pull-right ">Bientôt</span></a>

      </li>

      <li><a><i class="fa fa-desktop"></i> Carriere <span class="label label-info pull-right">Bientôt</span></a>

      </li>
      <li><a><i class="fa fa-magic"></i> Votre Reve <span class="label label-info pull-right">Bientôt</span></a>

      </li>

      <li><a><i class="fa fa-file-o"></i> Contrat <span class="label label-info pull-right ">Bientôt</span></a>

      </li>


    </ul>
  </div>


</div>
<!-- /sidebar menu -->

<!-- /menu footer buttons -->
<div class="sidebar-footer hidden-small">
  <a data-toggle="tooltip" data-placement="top" title="Settings">
    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="FullScreen">
    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Lock">
    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
  </a>
</div>
<!-- /menu footer buttons -->

app/views/layouts/shared/_topnav.html.erb
<div class="nav toggle">
  <a id="menu_toggle"><i class="fa fa-bars"></i></a>
</div>

<ul class="nav navbar-nav navbar-right">
  <li class="">
    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      <img src="<%= current_user.image.url %>" alt=""><%= current_user.first_name %> <%= current_user.last_name %>
      <span class=" fa fa-angle-down"></span>
    </a>
    <ul class="dropdown-menu dropdown-usermenu pull-right">
      <li>
        <a href="<%= user_path(current_user.id) %>">
          <% if current_user.activate %>
            <span class="badge bg-green pull-right">Activé</span>
          <% else %>
            <span class="badge bg-red pull-right">Non Activé</span>
          <% end %>
          <span>Profile</span>
        </a>
      </li>
      <li><%= link_to destroy_user_session_path, :method => 'delete' do%><i class="fa fa-sign-out pull-right"></i>Déconnexion<%end%></li>

    </ul>
  </li>
  <%if current_user.role == "admin"%>
  <li><a href="/sales/12565/index2"><i class="fa fa-send"></i> Les commandes reçues <span class="label label-danger pull-right"><%= Sale.where(env: true, read: nil).length %></span></a></li>
    <%end%>
<!--  <li role="presentation" class="dropdown">
    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
      <i class="fa fa-envelope-o"></i>
      <span class="badge bg-green">6</span>
    </a>
    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
      <li>
        <a>
          <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <div class="text-center">
          <a>
            <strong>See All Alerts</strong>
            <i class="fa fa-angle-right"></i>
          </a>
        </div>
      </li>
    </ul>
  </li>-->
</ul>