config/routes.rb
Rails.application.routes.draw do




  get 'our_partners/index'

  get 'confirmation/index'

  get 'send/index'

  resources :sales
  resources :banks
  devise_for :users , controllers: {
      registrations: 'users/registrations'
  }


  root 'welcome#welcome'
  get 'welcome/welcome'
  resources :products
  resources :users
  resources :sale_products

  get '/users/reset_password/:id' , to: 'users#reset_password'
  get '/users/active/:id' , to: 'users#active'
  get '/users/superactive/:id' , to: 'users#superactive'
  get '/send/index' , to: 'send#index'
  get 'clean' => "products#clean"
  get '/sales/12565/index2' , to: 'sales#index2'

  get '/send/:id/sell' , to: 'send#sell'

  get '/sales/:id/read' , to: 'sales#read'


  get '/users/:id' , to: 'users#show'
  get '/tree/:id' , to: 'tree#index'
  get '/welcome/:id' , to: 'welcome#index'
  post  'saleproducts/create', to: 'saleproducts#create'
  get   'sale_products/:id/destroy/:product_id' , to: 'sale_products#destroy'
  get   'sale_products/:id/decrement/:product_id' , to: 'sale_products#decrement'
  get   'sale_products/:id/increment/:product_id' , to: 'sale_products#increment'

  get '/fetch_products' => 'products#from_category', as: 'fetch_products'
    get "/index.html" => "static#index"
    get "/index2.html" => "static#index2"
    get "/index3.html" => "static#index3"
    get "/form.html" => "static#form"
    get "/form_advanced.html" => "static#form_advanced"
    get "/tables.html" => "static#tables"
    get "/tables_dynamic.html" => "static#tables_dynamic"
    get "/general_elements.html" => "static#general_elements"
    get "/media_gallery.html" => "static#media_gallery"
    get "/typography.html" => "static#typography"
    get "/icons.html" => "static#icons"
    get "/glyphicons.html" => "static#glyphicons"
    get "/widgets.html" => "static#widgets"
    get "/invoice.html" => "static#invoice"
    get "/inbox.html" => "static#inbox"
    get "/calendar.html" => "static#calendar"
    get "/chartjs.html" => "static#chartjs"
    get "/chartjs2.html" => "static#chartjs2"
    get "/morisjs.html" => "static#morisjs"
    get "/echarts.html" => "static#echarts"
    get "/other_charts.html" => "static#other_charts"
    get "/fixed_sidebar.html" => "static#fixed_sidebar"
    get "/fixed_footer.html" => "static#fixed_footer"
    get "/kitchen_sink" => "static#kitchen_sink"
    get "/kitchen8_sink" => "static#kitchen8_sink"
    get   '/',                                    to: "static#index"
    get "/firms/mother_firms",                        to:'firms#mother_firms'
    get "/firms/_categories",                        to:'firms#_categories'
    get "/banks/25/send_activation",              to:'banks#send_activation' , as: "send_activation"
    post  'banks/activations', to: 'banks#activations'
    post  'users/activations' , to: 'users#activations'
    post  'confirmation/ID' , to: 'confirmation#ID'


end

app/models/bank.rb
class Bank < ApplicationRecord
  belongs_to :user
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit]
  before_action :authenticate_user!
  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.where(user_id: current_user.id, activation: nil).order(date: :desc)
    @banks2 = Bank.where(user_id: current_user.id , points: nil).order(date: :desc)
  end

  # GET /banks/1
  # GET /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end


  # POST /banks
  # POST /banks.json
  def create
    @bank = Bank.new(bank_params)
    @bank.user_id = current_user.id
    @bank.date = Date.today
    @user =User.find(current_user.id)
    e= bank_params[:points]
    @user.points -= bank_params[:points].to_i
    @user.save
    respond_to do |format|
      if @bank.save
        format.html { redirect_to banks_path, notice: 'Vos points ont bien envoyés.' }

      else
        format.html { render :new }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  def send_activation
    @bank = Bank.new
  end

  def activations
    @bank = Bank.new(bank_param)
    @bank.user_id = current_user.id
    @bank.date = Date.today
    @re_user = User.find_by_randomID bank_param[:receiver_id]
    if @re_user
    @re_user.number_activation += bank_param[:activation].to_i
    @re_user.save!
    @tr_user = User.find_by_id current_user.id
    @tr_user.number_activation -= bank_param[:activation].to_i
    @tr_user.save!
    respond_to do |format|
      if @bank.save
        format.html { redirect_to banks_path, notice: 'Activations bien envoyé.' }
      else
        format.html { render :new }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
    else
      redirect_to banks_path,  alert: "Partenaire non trouvé ."
    end

  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:date, :points, :user_id,:receiver_id,:activation)
    end

  def bank_param
    params.permit(:date, :points, :user_id,:receiver_id,:activation)
  end



end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_form.html.erb
<div class="x_content">
<%= form_with(model: bank, local: true) do |form| %>
  <% if bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
      <% bank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :points, 'Points' %>
    <%= form.text_field :points, id: :bank_points , class: 'form-control'%>
  </div>

<br>
  <div class="actions">
    <%= form.submit 'Transfaire', class: 'form-control btn btn-success'%>
  </div>
<% end %>
</div>

app/views/banks/edit.html.erb
<h1>Editing Bank</h1>

<%= render 'form', bank: @bank %>

<%= link_to 'Show', @bank %> |
<%= link_to 'Back', banks_path %>

app/views/banks/index.html.erb
<div class="col-md-6 col-sm-6 col-xs-12">
  <%= link_to 'Transfere de fond', new_bank_path , class: 'form-control btn btn-success'%>
</div>
<div class="col-md-6 col-sm-6 col-xs-12">
  <%= link_to 'Transfere des activations', "/banks/25/send_activation", class: 'form-control btn btn-primary' %>
</div>



<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Mes points transferés </h2>


      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
        <thead>
        <tr>
          <th>Date</th>
          <th>Points</th>
        </tr>
        </thead>

        <tbody>
        <% @banks.each do |bank| %>
          <tr>
            <td><%= bank.date.strftime("%d-%m-%Y") %></td>
            <td><%= bank.points %></td>

          </tr>
        <% end %>
        </tbody>
      </table>


    </div>
  </div>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Mes activations transferées </h2>


      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <table id="datatable-responsive2" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
        <thead>
        <tr>
          <th>Date</th>
          <th>Nombre d'activation</th>
          <th>Pour</th>
        </tr>
        </thead>

        <tbody>
        <% @banks2.each do |bank| %>
          <tr>
            <td><%= bank.date.strftime("%d-%m-%Y") %></td>
            <td><%= bank.activation %></td>
            <td><%= User.find_by_randomID(bank.receiver_id).last_name %> <%= User.find_by_randomID(bank.receiver_id).first_name %></td>

          </tr>
        <% end %>
        </tbody>
      </table>


    </div>
  </div>
</div>


<script>
    $('#datatable-responsive2').DataTable();
</script>
<script>

        function init_PNotify() {
            console.log('init_PNotify');

            if( "<%= notice%>" == "") {
                new PNotify({

                    title: 'Bienvenue à la banque',
                    text: 'Vous trouverez ici vos points transferés ainsi vos activations transferées',
                    type: 'info',
                    styling: 'bootstrap3'
                });

            }
            

    }

</script>

app/views/banks/new.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Faire un transfaire </h2>


      <div class="clearfix"></div>
    </div>

    <%= render 'form', bank: @bank %>

<%#= link_to 'Back', sales_path , class: 'btn btn-danger'%>
  </div>
</div>

app/views/banks/send_activation.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Faire un transfaire </h2>


      <div class="clearfix"></div>
    </div>
    <div class="x_content">

      <%= form_tag(banks_activations_path, {:method => :post}) do %>


      <div class="field">
        <%= label_tag :activation, 'Nombre dactivation' %>
        <%= text_field_tag :activation, nil, {class: "form-control", placeholder: "Nombre dactivation"} %>
      </div>

      <br>


      <div class="field">
        <%= label_tag :receiver_id, 'ID du recepteur' %>
        <%= text_field_tag :receiver_id, nil, {class: "form-control", placeholder: "ID du recepteur"} %>
      </div>



      <br>
      <div class="actions">
        <%= submit_tag 'Envoyer', class: ' form-control btn btn-success' %>
      </div>

   <%end%>


    </div>
<%#= link_to 'Back', sales_path , class: 'btn btn-danger'%>
  </div>
</div>

app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @bank.date %>
</p>

<p>
  <strong>Points:</strong>
  <%= @bank.points %>
</p>

<p>
  <strong>User:</strong>
  <%= @bank.user_id %>
</p>

<%= link_to 'Edit', edit_bank_path(@bank) %> |
<%= link_to 'Back', banks_path %>