config/routes.rb
Rails.application.routes.draw do




  get 'our_partners/index'

  get 'confirmation/index'

  get 'send/index'

  resources :sales
  resources :banks
  devise_for :users , controllers: {
      registrations: 'users/registrations'
  }


  root 'welcome#welcome'
  get 'welcome/welcome'
  resources :products
  resources :users
  resources :sale_products

  get '/users/reset_password/:id' , to: 'users#reset_password'
  get '/users/active/:id' , to: 'users#active'
  get '/users/superactive/:id' , to: 'users#superactive'
  get '/send/index' , to: 'send#index'
  get 'clean' => "products#clean"
  get '/sales/12565/index2' , to: 'sales#index2'

  get '/send/:id/sell' , to: 'send#sell'

  get '/sales/:id/read' , to: 'sales#read'


  get '/users/:id' , to: 'users#show'
  get '/tree/:id' , to: 'tree#index'
  get '/welcome/:id' , to: 'welcome#index'
  post  'saleproducts/create', to: 'saleproducts#create'
  get   'sale_products/:id/destroy/:product_id' , to: 'sale_products#destroy'
  get   'sale_products/:id/decrement/:product_id' , to: 'sale_products#decrement'
  get   'sale_products/:id/increment/:product_id' , to: 'sale_products#increment'

  get '/fetch_products' => 'products#from_category', as: 'fetch_products'
    get "/index.html" => "static#index"
    get "/index2.html" => "static#index2"
    get "/index3.html" => "static#index3"
    get "/form.html" => "static#form"
    get "/form_advanced.html" => "static#form_advanced"
    get "/tables.html" => "static#tables"
    get "/tables_dynamic.html" => "static#tables_dynamic"
    get "/general_elements.html" => "static#general_elements"
    get "/media_gallery.html" => "static#media_gallery"
    get "/typography.html" => "static#typography"
    get "/icons.html" => "static#icons"
    get "/glyphicons.html" => "static#glyphicons"
    get "/widgets.html" => "static#widgets"
    get "/invoice.html" => "static#invoice"
    get "/inbox.html" => "static#inbox"
    get "/calendar.html" => "static#calendar"
    get "/chartjs.html" => "static#chartjs"
    get "/chartjs2.html" => "static#chartjs2"
    get "/morisjs.html" => "static#morisjs"
    get "/echarts.html" => "static#echarts"
    get "/other_charts.html" => "static#other_charts"
    get "/fixed_sidebar.html" => "static#fixed_sidebar"
    get "/fixed_footer.html" => "static#fixed_footer"
    get "/kitchen_sink" => "static#kitchen_sink"
    get "/kitchen8_sink" => "static#kitchen8_sink"
    get   '/',                                    to: "static#index"
    get "/firms/mother_firms",                        to:'firms#mother_firms'
    get "/firms/_categories",                        to:'firms#_categories'
    get "/banks/25/send_activation",              to:'banks#send_activation' , as: "send_activation"
    post  'banks/activations', to: 'banks#activations'
    post  'users/activations' , to: 'users#activations'
    post  'confirmation/ID' , to: 'confirmation#ID'


end

app/models/product.rb
class Product < ApplicationRecord


  has_many :sale_products
  has_many :sales , through: :sale_products

  has_attached_file :img , :styles => { :small => "150x150>" }

  validates_attachment_content_type :img, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]



  CATEGORIES  = %w(Vetement Automobile)
  CATEGORIES2  = %w(Tout Vetement Automobile)

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @products2 = Product.paginate(page: params[:page], per_page: 5)
    
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  def clean
    redirect_to products_path, notice: 'Votre pack de formation a été bien activé.'
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def from_category
    if params[:name] == 'Tout'
      @selected = Product.paginate(page: params[:page], per_page: 5)
    else
      @selected = Product.paginate(page: params[:page], per_page: 5).where("category LIKE ?", "#{params[:name]}%")
    end
    respond_to do |format|
      format.js
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name,:img,:price,:category)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="x_content">
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name, class: 'form-control', placeholder: 'Enter name ...' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control', placeholder: 'Enter price ...' %>
  </div>

  <div class="form-group">
    <%= form.label :category, "Category" %>
    <%= form.select :category, Product::CATEGORIES.select {|d| [ d[0],d[1] ]} , { prompt: "Choisissez la category " }, {class: 'form-control', required: true} %>
  </div>
  <div class="form-group">
    <%= form.label :img %>
    <%= form.file_field :img %>
  </div>
 <br>

  <div class="form-group actions">
    <%= form.submit 'Ajouter', :class => 'btn btn-lg btn-success btn-block' %>
  </div>
<% end %>
</div>

app/views/products/_item_grid.html.erb
<div id="products_grid">
  <%= render partial: 'products_list', locals: { products: products } %>
</div>

app/views/products/_products_list.html.erb
<% products.in_groups_of(4) do |group| %>

  <div class="row">
    <% group.each do |product| %>
      <div class="col-md-3">
        <%if product%>
        <div class="product-item">
          <div class="pi-img-wrapper">
            <img src="<%=product.img.url if product%>" class="img-responsive" >
            <div>
              <a <%= link_to "Voir détails", product , class:"btn"%></a>
            </div>
          </div>
          <h3><i><b><%=product.name if product%></b></i></h3>
          <div class="pi-price"><%=product.price if product%> DZD</div>

          <div class="sticker sticker-new"></div>
        </div>
          <%end%>
      </div>
    <%end%>
  </div>
<%end%>

<%= will_paginate products %>

app/views/products/_sidebar_menu.html.erb
<% Product::CATEGORIES2.each do | cat | %>
  <%= link_to cat, fetch_products_path(:name => cat), :remote => true ,class: "btn btn-default filter-button" %>

<% end %>

app/views/products/edit.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2> Modifier " <%= @product.name %> " | </h2> <%= link_to 'Show', @product, class: 'btn btn-info' %>
      | <%= link_to 'Back', products_path, class: 'btn btn-danger' %>
    </div>




<%= render 'form', product: @product %>

  </div>
</div>

app/views/products/from_category.js.erb
$("#products_grid").html("<%= escape_javascript(render partial: 'products_list', locals: { products: @selected } ) %>");

app/views/products/index.html.erb
<%if current_user.role == "admin"%>
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Produits et services </h2> <h2> | </h2> <%= link_to 'Nouveau produit', new_product_path ,class:"btn btn-primary"%>

      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
        <thead>
        <tr>
          <th>Raison</th>
          <th>Category</th>
          <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.category%></td>
            <td><%= link_to 'Show', product, class:"btn btn-primary" %>
            <%= link_to 'Edit', edit_product_path(product) ,class:"btn btn-default"%>
            <%= link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you sure?'},class:"btn btn-danger" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>


    </div>
  </div>
</div>
<%end%>
<div class="row">
<div class="col-md-12 col-sm-12 col-xs-12">

<!--<a href="<%#= new_sale_path%>" class="btn btn-default btn-lg btn3d pull-right">
  <i class="fa fa-shopping-cart"></i> Faire une commande
</a>-->
</div>
</div>

 <!--    <div class="col-md-4">
      <div class="product-item">
        <div class="pi-img-wrapper">
          <img src="http://keenthemes.com/assets/bootsnipp/k2.jpg" class="img-responsive" alt="Berry Lace Dress">
          <div>
            <a href="#" class="btn">Zoom</a>
            <a href="#" class="btn">View</a>
          </div>
        </div>
        <h3><a href="shop-item.html">Berry Lace Dress</a></h3>
        <div class="pi-price">$29.00</div>
        <a href="javascript:;" class="btn add2cart">Add to cart</a>
      </div>
    </div>
    <div class="col-md-4">
      <div class="product-item">
        <div class="pi-img-wrapper">
          <img src="http://keenthemes.com/assets/bootsnipp/k3.jpg" class="img-responsive" alt="Berry Lace Dress">
          <div>
            <a href="#" class="btn">Zoom</a>
            <a href="#" class="btn">View</a>
          </div>
        </div>
        <h3><a href="shop-item.html">Berry Lace Dress</a></h3>
        <div class="pi-price">$29.00</div>
        <a href="javascript:;" class="btn add2cart">Add to cart</a>
      </div>
    </div>-->

<div class="container">
  <div class="row">
    <div class="gallery col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h1 class="gallery-title">Nos produits</h1>
    </div>

    <div align="center">
      <%#= render 'sidebar_menu' %>
      <a href="clean" class="btn btn-default btn-lg btn3d ">
        <i class="fa fa-check"></i> Active mon Pack formation
      </a>

    </div>
    <br/>

    <%= render partial: 'item_grid', locals: {products: @products2} %>

  </div>
</div>




<style>

  /***
  User Profile Sidebar by @keenthemes
  A component of Metronic Theme - #1 Selling Bootstrap 3 Admin Theme in Themeforest: http://j.mp/metronictheme
  Licensed under MIT
  ***/


  .product-item {
    padding: 15px;
    background: #fff;
    margin-top: 20px;
    position: relative;
  }

  .product-item:hover {
    box-shadow: 5px 5px rgba(234, 234, 234, 0.9);
  }

  .product-item:after {
    content: ".";
    display: block;
    height: 0;
    clear: both;
    visibility: hidden;
    font-size: 0;
    line-height: 0;
  }

  .sticker {
    position: absolute;
    top: 0;
    left: 0;
    width: 63px;
    height: 63px;
  }

  .sticker-new {
    background: url(http://keenthemes.com/assets/bootsnipp/new.png) no-repeat;
    left: auto;
    right: 0;
  }

  .pi-img-wrapper {
    position: relative;
  }

  .pi-img-wrapper div {
    background: rgba(0, 0, 0, 0.3);
    position: absolute;
    left: 0;
    top: 0;
    display: none;
    width: 100%;
    height: 100%;
    text-align: center;
  }

  .product-item:hover > .pi-img-wrapper > div {
    display: block;
  }

  .pi-img-wrapper div .btn {
    padding: 3px 10px;
    color: #fff;
    border: 1px #fff solid;
    margin: -13px 5px 0;
    background: transparent;
    text-transform: uppercase;
    position: relative;
    top: 50%;
    line-height: 1.4;
    font-size: 12px;
  }

  .product-item .btn:hover {
    background: #e84d1c;
    border-color: #c8c8c8;
  }

  .product-item h3 {
    font-size: 14px;
    font-weight: 300;
    padding-bottom: 4px;
    text-transform: uppercase;
  }

  .product-item h3 a {
    color: #3e4d5c;
  }

  .product-item h3 a:hover {
    color: #E02222;
  }

  .pi-price {
    color: #e84d1c;
    font-size: 18px;
    float: left;
    padding-top: 1px;
  }



  .gallery-title
  {
    font-size: 36px;
    color: #73879c;
    text-align: center;
    font-weight: 500;
    margin-bottom: 70px;
  }
  .gallery-title:after {
    content: "";
    position: absolute;
    width: 7.5%;
    left: 46.5%;
    height: 45px;
    border-bottom: 1px solid #5e5e5e;
  }
  .filter-button
  {
    font-size: 18px;
    border: 1px solid #73879c;
    border-radius: 5px;
    text-align: center;
    color: #73879c;
    margin-bottom: 30px;

  }
  .filter-button:hover
  {
    font-size: 18px;
    border: 1px solid #73879c;
    border-radius: 5px;
    text-align: center;
    color: #ffffff;
    background-color: #73879c;

  }
  .btn-default:active .filter-button:active
  {
    background-color: #73879c;
    color: white;
  }

  .port-image
  {
    width: 100%;
  }

  .gallery_product
  {
    margin-bottom: 30px;
  }


</style>


<style>
  .btn3d {
    position: relative;
    top: -6px;
    border: 0;
    transition: all 40ms linear;
    margin-top: 10px;
    margin-bottom: 10px;
    margin-left: 2px;
    margin-right: 2px;
  }

  .btn3d:active:focus,
  .btn3d:focus:hover,
  .btn3d:focus {
    -moz-outline-style: none;
    outline: medium none;
  }

  .btn3d:active, .btn3d.active {
    top: 2px;
  }


  .btn3d.btn-default {
    color: #73879c;
    box-shadow: 0 0 0 1px #ebebeb inset, 0 0 0 2px rgba(255, 255, 255, 0.10) inset, 0 8px 0 0 #BEBEBE, 0 8px 8px 1px rgba(0, 0, 0, .2);
    background-color: #f9f9f9;
  }

  .btn3d.btn-default:active, .btn3d.btn-default.active {
    color: #73879c;
    box-shadow: 0 0 0 1px #ebebeb inset, 0 0 0 1px rgba(255, 255, 255, 0.15) inset, 0 1px 3px 1px rgba(0, 0, 0, .1);
    background-color: #f9f9f9;
  }



</style>

app/views/products/new.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Nouveau Produit </h2>


      <div class="clearfix"></div>
    </div>

<%#= link_to 'Back', products_path , class: 'btn btn-danger'%>

<%= render 'form', product: @product %>

</div>
  </div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Retour a la liste des produits', products_path %>




<div class="">


  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">

        <div class="x_content">

          <div class="col-md-7 col-sm-7 col-xs-12">
            <div class="product-image">
              <%= image_tag @product.img.url %>
            </div>
            <div class="product_gallery">
              <a>
                <%= image_tag @product.img.url %>
              </a>
              <a>
                <%= image_tag @product.img.url %>
              </a>
              <a>
                <%= image_tag @product.img.url %>
              </a>
              <a>
                <%= image_tag @product.img.url %>
              </a>
            </div>
          </div>

          <div class="col-md-5 col-sm-5 col-xs-12" style="border:0px solid #e5e5e5;">

            <h3 class="prod_title"> <%= @product.name %></h3>

            <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua
              butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terr.</p>
            <br/>

            <div class="">
              <h2>Available Colors</h2>
              <ul class="list-inline prod_color">
                <li>
                  <p>Green</p>
                  <div class="color bg-green"></div>
                </li>
                <li>
                  <p>Blue</p>
                  <div class="color bg-blue"></div>
                </li>
                <li>
                  <p>Red</p>
                  <div class="color bg-red"></div>
                </li>
                <li>
                  <p>Orange</p>
                  <div class="color bg-orange"></div>
                </li>

              </ul>
            </div>
            <br/>

            <div class="">
              <h2>Size
                <small>Please select one</small>
              </h2>
              <ul class="list-inline prod_size">
                <li>
                  <button type="button" class="btn btn-default btn-xs">Small</button>
                </li>
                <li>
                  <button type="button" class="btn btn-default btn-xs">Medium</button>
                </li>
                <li>
                  <button type="button" class="btn btn-default btn-xs">Large</button>
                </li>
                <li>
                  <button type="button" class="btn btn-default btn-xs">Xtra-Large</button>
                </li>
              </ul>
            </div>
            <br/>

            <div class="">
              <div class="product_price">
                <h1 class="price"><%= @product.price %> DZA</h1>
                <span class="price-tax">Ex Tax: <%= @product.price %> DZA</span>
                <br>
              </div>
            </div>

            <div class="">
              <button type="button" class="btn btn-default btn-lg">Add to Cart</button>
              <button type="button" class="btn btn-default btn-lg">Add to Wishlist</button>
            </div>

            <div class="product_social">
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-facebook-square"></i></a>
                </li>
                <li><a href="#"><i class="fa fa-twitter-square"></i></a>
                </li>
                <li><a href="#"><i class="fa fa-envelope-square"></i></a>
                </li>
                <li><a href="#"><i class="fa fa-rss-square"></i></a>
                </li>
              </ul>
            </div>

          </div>


          <div class="col-md-12">

            <div class="" role="tabpanel" data-example-id="togglable-tabs">
              <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                <li role="presentation" class="active">
                  <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Home</a>
                </li>
                <li role="presentation" class="">
                  <a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Profile</a>
                </li>
                <li role="presentation" class="">
                  <a href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">Profile</a>
                </li>
              </ul>
              <div id="myTabContent" class="tab-content">
                <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                  <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown
                    aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica.
                    Reprehenderit butcher retro keffiyeh dreamcatcher
                    synth. Cosby sweater eu banh mi, qui irure terr.</p>
                </div>
                <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                  <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.
                    Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four
                    loko farm-to-table craft beer twee. Qui photo
                    booth letterpress, commodo enim craft beer mlkshk aliquip</p>
                </div>
                <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
                  <p>xxFood truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.
                    Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four
                    loko farm-to-table craft beer twee. Qui
                    photo booth letterpress, commodo enim craft beer mlkshk </p>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>