config/routes.rb
Rails.application.routes.draw do




  get 'our_partners/index'

  get 'confirmation/index'

  get 'send/index'

  resources :sales
  resources :banks
  devise_for :users , controllers: {
      registrations: 'users/registrations'
  }


  root 'welcome#welcome'
  get 'welcome/welcome'
  resources :products
  resources :users
  resources :sale_products

  get '/users/reset_password/:id' , to: 'users#reset_password'
  get '/users/active/:id' , to: 'users#active'
  get '/users/superactive/:id' , to: 'users#superactive'
  get '/send/index' , to: 'send#index'
  get 'clean' => "products#clean"
  get '/sales/12565/index2' , to: 'sales#index2'

  get '/send/:id/sell' , to: 'send#sell'

  get '/sales/:id/read' , to: 'sales#read'


  get '/users/:id' , to: 'users#show'
  get '/tree/:id' , to: 'tree#index'
  get '/welcome/:id' , to: 'welcome#index'
  post  'saleproducts/create', to: 'saleproducts#create'
  get   'sale_products/:id/destroy/:product_id' , to: 'sale_products#destroy'
  get   'sale_products/:id/decrement/:product_id' , to: 'sale_products#decrement'
  get   'sale_products/:id/increment/:product_id' , to: 'sale_products#increment'

  get '/fetch_products' => 'products#from_category', as: 'fetch_products'
    get "/index.html" => "static#index"
    get "/index2.html" => "static#index2"
    get "/index3.html" => "static#index3"
    get "/form.html" => "static#form"
    get "/form_advanced.html" => "static#form_advanced"
    get "/tables.html" => "static#tables"
    get "/tables_dynamic.html" => "static#tables_dynamic"
    get "/general_elements.html" => "static#general_elements"
    get "/media_gallery.html" => "static#media_gallery"
    get "/typography.html" => "static#typography"
    get "/icons.html" => "static#icons"
    get "/glyphicons.html" => "static#glyphicons"
    get "/widgets.html" => "static#widgets"
    get "/invoice.html" => "static#invoice"
    get "/inbox.html" => "static#inbox"
    get "/calendar.html" => "static#calendar"
    get "/chartjs.html" => "static#chartjs"
    get "/chartjs2.html" => "static#chartjs2"
    get "/morisjs.html" => "static#morisjs"
    get "/echarts.html" => "static#echarts"
    get "/other_charts.html" => "static#other_charts"
    get "/fixed_sidebar.html" => "static#fixed_sidebar"
    get "/fixed_footer.html" => "static#fixed_footer"
    get "/kitchen_sink" => "static#kitchen_sink"
    get "/kitchen8_sink" => "static#kitchen8_sink"
    get   '/',                                    to: "static#index"
    get "/firms/mother_firms",                        to:'firms#mother_firms'
    get "/firms/_categories",                        to:'firms#_categories'
    get "/banks/25/send_activation",              to:'banks#send_activation' , as: "send_activation"
    post  'banks/activations', to: 'banks#activations'
    post  'users/activations' , to: 'users#activations'
    post  'confirmation/ID' , to: 'confirmation#ID'


end

app/models/sale.rb
class Sale < ApplicationRecord
  has_many :sale_products
  has_many :products, through: :sale_products
  belongs_to :user




end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy,:read]
  before_action :authenticate_user!
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.where(env: nil, user_id: current_user.id)
  end

  def index2
    @salesread = Sale.where(env: true)

  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @ven_pros = @sale.sale_products.order(:quantity)
    @products = Product.all
    @sale_item = @sale.sale_products.new




    @sar = SaleProduct.where sale_id: @sale.id

    respond_to do |format|
      format.html
      format.pdf {render pdf: "sale",
                         template: "sales/sale.pdf.erb",
                         locals: {:sale => @sale}}
      end



    end

  # GET /sales/new
  def new
    @sale = Sale.new


  end

  # GET /sales/1/edit
  def edit

  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)
    @sale.total_price = 0;
    @sale.date = Date.today
    @sale.user_id = current_user.id

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'La commande a été créée avec succès.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)

        format.html { redirect_to @sale, notice: 'La commande a été modifiée avec succès.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def read
    @s = @sale
    @s.read = true
    @s.save
    redirect_to "/sales/12565/index2", notice: "Commande Bien vu."



  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:date, :total_price, :contact_name)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
    <div class="x_content">


      <%= form_with(model: sale, local: true) do |form| %>
        <% if sale.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

            <ul>
              <% sale.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>


        <div class="field">
          <%= form.label :contact_name ,'Nom du client'%>
          <%= form.text_field :contact_name, id: :sale_contact_name , class: 'form-control'%>
        </div>

        <br>

        <div class="actions">
          <%= form.submit 'Créer la commande', class: 'form-control btn btn-success'%>
        </div>
      <% end %>
    </div>

app/views/sales/edit.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Modifier la commande | </h2>  <%= link_to 'Mes commandes', sales_path ,class:'btn btn-warning'%>
    </div>
<%= render 'form', sale: @sale %>

<%#= link_to 'Show', @sale %>


  </div>
</div>

app/views/sales/index.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Mon Pannier </h2>


      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
        <thead>
        <tr>
          <th>Date</th>
          <th>Total price</th>
          <th>Contact name</th>
          <th>Action</th>
        </tr>
        </thead>

        <tbody>
        <% @sales.each do |sale| %>
          <tr>
            <td><%= sale.date %></td>
            <td><%= sale.total_price %></td>
            <td><%= sale.contact_name %></td>
            <td><%= link_to 'Show', sale ,class:"btn btn-primary" %>
            <%= link_to 'Edit', edit_sale_path(sale) ,class:"btn btn-default" %>
            <%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %>
              <%= link_to ' Envoyer ', "/send/#{sale.id}/sell", class: "btn btn-md btn-success "%>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>


    </div>
  </div>
</div>

app/views/sales/index2.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
  <br>
  <%if notice%>
    <div class="alert alert-info alert-dismissible fade in">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%= notice %>
    </div>
  <%end%>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Les commandes reçues </h2>


      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
        <thead>
        <tr>
          <th>Date</th>
          <th>Total price</th>
          <th>Contact name</th>
          <th>Action</th>
        </tr>
        </thead>

        <tbody>
        <% @salesread.each do |sale| %>
          <tr>
            <td><%= sale.date %></td>
            <td><%= sale.total_price %></td>
            <td><%= sale.contact_name %></td>
            <td>
             <%unless sale.read == true%> <%= link_to ' Vu ', "/sales/#{sale.id}/read", class: "btn btn-md btn-success " %> <%end%>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>


    </div>
  </div>
</div>

app/views/sales/new.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Nouvelle commande </h2>


      <div class="clearfix"></div>
    </div>

<%= render 'form', sale: @sale %>

<%#= link_to 'Back', sales_path , class: 'btn btn-danger'%>
  </div>
</div>

app/views/sales/sale.pdf.erb
<!DOCTYPE html>
<meta charset="utf-8"  />
<html>
<style>
  table {
    border-collapse: collapse;
    width: 100%;

  }
  th, td {
    border: 1px solid black;
    font-size: 13px;
    height: 50px;
  }
  h4 {
    line-height: 0.3;
    font-family: "Times New Roman", Times, serif;
    display: inline-block;
    height:100%;
    width:35%;

  }
  p {
    line-height: 0.3;
    font-family: "Times New Roman", Times, serif;
    font-size: 10px;
    display: inline-table;
    height:50%;
    width:50%;
  }
</style>

<h3 align="center">BON DE LIVRAISON N <%=@sale.id%></h3>
<h4 aria-live="left">LIGHT_HOUSE</h4>
<br>
<P style="float: left">SOLUTION XXXXXXX & XXXXXXXX</P>
<p style="float: right">RIB:00697 300694 30059</p>
<p style="float: right">RC N° 00/00 0092212B16</p>
<p style="float: left">11 Rue XXXXX XXXXXX-Wilaya-Algeria</p>
<p style="float: right">NIF:001619009221266 </p>
<p style="float: right">TEL/FAX:+213 00 00 00 00 - MOB:0XXX XX XX XX </p>
<p style="float: left">E-mail: contact@contact.com </p>
<p style="float: right">Art.Imp:1901612502 </p>

<table class="table">
  <thead>
  <tr>

    <th>Designations</th>
    <th>Quantités<br>commandées</th>
    <th>Prix Produit</th>
    <th>Prix Achete</th>

  </tr>
  </thead>
  <tbody>
  <% @ven_pros.each { |s| %>
    <tr>

      <td align="center"><%= s.product.name %></td>
      <td align="center"><%= s.quantity %></td>
      <td align="center"><%= s.price %> DZD</td>
      <td align="center"><%= s.price * s.quantity%> DZD</td>

  <% } %>
  </tbody>
</table>
<br>
<h4 style="float: left"> Le prix Total: <%=@sale.total_price%></h4>
<h4 style="float: right"> Livré le:  <%=@sale.date%></h4>
<br>
<br>

</html>

app/views/sales/show.html.erb
<%= link_to 'Modifier la commande', edit_sale_path(@sale) ,class:"btn btn-primary"%> |
<%= link_to 'Back', sales_path ,class:"btn btn-warning"%> |
<a class="btn btn-success" data-toggle="modal" href="#betaModal">Ajouter des produits </a>
<div id="betaModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">×</button>
        <h3 class="text-center">Produits & Services</h3>
      </div>
      <div class="modal-body">
        <div class="row">
          <%= form_tag(saleproducts_create_path, {method: :post}) do %>


            <% @products.in_groups_of(4) do |group| %>

              <div class="row">
                <% group.each do |product| %>
                  <div class="col-md-3">
                    <%if product%>
                    <div class="product-item">
                      <div class="pi-img-wrapper">
                        <img src="<%=product.img.url if product%>" class="img-responsive" >
                        <div>
                          <a <%= link_to "Voir détails", product , class:"btn"%></a>
                        </div>
                      </div>
                      <h3><i ><b><%=product.name if product%></b></i></h3>
                      <div class="pi-price"><%=product.price if product%> DZD</div>
                      <%= form_for @sale_item do |f| %>
                        <%= f.hidden_field :sale_id, value: @sale.id %>

                        <%=  f.hidden_field :product_id, value: product.id if product%>

                        <%= f.number_field :quantity, class:"form-control" %>
                        <br>
                        <%= f.submit "+ Ajouter", class: "btn add2cart" %>
                      <% end %>
                      <div class="sticker sticker-new"></div>
                    </div>
                    <%end%>
                  </div>
                <%end%>
              </div>
            <%end%>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<div role="main">
  <div class="">


    <div class="row">
      <div class="col-md-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Commande pour le client "<%=@sale.contact_name%>"</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">

            <section class="content invoice">
              <!-- title row -->
              <div class="row">
                <div class="col-xs-12 invoice-header">
                  <h1>
                    <i class="fa fa-globe"></i> Commande.
                    <small class="pull-right">Date: <%= @sale.date %></small>
                  </h1>
                </div>
                <!-- /.col -->
              </div>
              <!-- info row -->
              <div class="row invoice-info">
                <div class="col-sm-4 invoice-col">
                  De la part de :
                  <address>
                    <strong>Light-House .</strong>
                    <br>795 Setif, rue 600
                    <br>Algerie, CA 94107
                    <br>Telephone: XXXXXXX
                    <br>Email: nimportkoi@admin.com
                  </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                  Pour (Mr/Mm/Melle)
                  <address>
                    <strong><%= @sale.contact_name%></strong>
                    <br>Information client
                    <br>Information client
                    <br>Information client
                    <br>Information client
                  </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                  <b>Commande Num <%= @sale.id%></b>
                  <br>
                  <br>
                  <b>Faite par:</b> <%= @sale.user.first_name %> <%= @sale.user.last_name %>
                  <br>
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <!-- Table row -->
              <div class="row">
                <div class="col-xs-12 table">
                  <table class="table table-striped">
                    <tr>
                      <th>Produit</th>
                      <th>Quantité</th>
                      <th>prix</th>
                      <th>partial price</th>
                      <th>Modifier quantité</th>
                      <th>Action</th>
                    </tr>
                    <tbody>
                    <% @ven_pros.each {|s| %>
                      <tr>
                        <td><%= s.product.name %></td>
                        <td><%= s.quantity %></td>
                        <td><%= s.price %> DZD</td>
                        <td><%= s.price * s.quantity %> DZD</td>
                        <td><%= link_to ' - ', "/sale_products/#{params[:id]}/decrement/#{s.id};", class: "btn btn-md btn-danger" %>
                          <%= link_to ' + ', "/sale_products/#{params[:id]}/increment/#{s.id};", class: "btn btn-md btn-primary" %></td>
                        <td><%= link_to 'Supprimer', "/sale_products/#{params[:id]}/destroy/#{s.id};", data: {confirm: 'Are you sure?'}, class: "btn btn-md btn-danger" %>
                        </td>
                      </tr>

                    <% } %>
                    </tbody>
                  </table>
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <div class="row">
                <!-- accepted payments column -->
                <div class="col-xs-6">
                  <p class="lead">Description:</p>

                  <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                    Description Description Description Description Description Description Description v v Description.
                  </p>
                </div>
                <!-- /.col -->
                <div class="col-xs-6">

                  <div class="table-responsive">
                    <table class="table">
                      <tbody>
                      <tr>
                        <th style="width:50%">Total:</th>
                        <td><%=@sale.total_price%> DZD</td>
                      </tr>
                      <tr>
                        <th>Tax (14%)</th>
                        <td><%=(@sale.total_price.to_i * 14)/ 100%> DZD</td>
                      </tr>
                      <tr>
                        <th>Total:</th>
                        <td><%= ((@sale.total_price.to_i * 14)/ 100) + @sale.total_price%> DZD</td>
                      </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <!-- this row will not appear when printing -->
              <div class="row no-print">
                <div class="col-xs-12">
                  <%= link_to 'Génerer un PDF' ,"",class:"btn btn-primary pull-right",onclick:"passvar()"%>
                  <%= link_to ' Envoyer ', "/send/#{params[:id]}/sell", class: "btn btn-md btn-success pull-right"%>

                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>







<style>

  /***
  User Profile Sidebar by @keenthemes
  A component of Metronic Theme - #1 Selling Bootstrap 3 Admin Theme in Themeforest: http://j.mp/metronictheme
  Licensed under MIT
  ***/


  .product-item {
    padding: 15px;
    background: #fff;
    margin-top: 20px;
    position: relative;
  }

  .product-item:hover {
    box-shadow: 5px 5px rgba(234, 234, 234, 0.9);
  }

  .product-item:after {
    content: ".";
    display: block;
    height: 0;
    clear: both;
    visibility: hidden;
    font-size: 0;
    line-height: 0;
  }

  .sticker {
    position: absolute;
    top: 0;
    left: 0;
    width: 63px;
    height: 63px;
  }

  .sticker-new {
    background: url(http://keenthemes.com/assets/bootsnipp/new.png) no-repeat;
    left: auto;
    right: 0;
  }

  .pi-img-wrapper {
    position: relative;
  }

  .pi-img-wrapper div {
    background: rgba(0, 0, 0, 0.3);
    position: absolute;
    left: 0;
    top: 0;
    display: none;
    width: 100%;
    height: 100%;
    text-align: center;
  }

  .product-item:hover > .pi-img-wrapper > div {
    display: block;
  }

  .pi-img-wrapper div .btn {
    padding: 3px 10px;
    color: #fff;
    border: 1px #fff solid;
    margin: -13px 5px 0;
    background: transparent;
    text-transform: uppercase;
    position: relative;
    top: 50%;
    line-height: 1.4;
    font-size: 12px;
  }

  .product-item .btn:hover {
    background: #e84d1c;
    border-color: #c8c8c8;
  }

  .product-item h3 {
    font-size: 14px;
    font-weight: 300;
    padding-bottom: 4px;
    text-transform: uppercase;
  }

  .product-item h3 a {
    color: #3e4d5c;
  }

  .product-item h3 a:hover {
    color: #E02222;
  }

  .pi-price {
    color: #e84d1c;
    font-size: 18px;
    float: left;
    padding-top: 1px;
  }

  .product-item .add2cart {
    float: left;
    color: #a8aeb3;
    border: 1px #ededed solid;
    padding: 3px 6px;
    text-transform: uppercase;
  }

  .product-item .add2cart:hover {
    color: #fff;
    background: #e84d1c;
    border-color: #e84d1c;
  }
</style>
<script>
    function passvar() {
        window.location = '/sales/<%=@sale.id%>.pdf';
    }
</script>